# Generated by Django 4.2.5 on 2023-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('game_desciption', models.CharField(blank=True, max_length=100, null=True)),
                ('game_image', models.ImageField(blank=True, null=True, upload_to='GIMAGE')),
            ],
        ),
    ]
