# Generated by Django 4.2.5 on 2023-10-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='game_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
